name: 'Simili - Issue Intelligence'
description: 'AI-powered duplicate detection and similar issue finder with cross-repo search.'
author: 'Kavirubc'

branding:
  icon: 'search'
  color: 'purple'

inputs:
  command:
    description: 'Command to run: "process" for similarity/transfer, "triage" for AI labeling/duplicates, "full-process" for unified pipeline'
    required: false
    default: 'process'
  config_path:
    description: 'Path to the simili configuration file'
    required: false
    default: '.github/simili.yaml'
  dry_run:
    description: 'Run in read-only mode without posting comments or making changes'
    required: false
    default: 'false'
  execute:
    description: 'For triage/full-process: execute actions (add labels, close duplicates). If false, only analyzes.'
    required: false
    default: 'true'
  github_token:
    description: 'GitHub token for API access. Use a GitHub App token for custom bot name.'
    required: false
    default: ${{ github.token }}
  transfer_token:
    description: 'GitHub token with elevated permissions for issue transfers. Falls back to github_token if not provided.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - --event-path
    - /github/workflow/event.json
    - --config
    - ${{ inputs.config_path }}
    - ${{ inputs.dry_run == 'true' && '--dry-run' || '' }}
    - ${{ (inputs.command == 'triage' || inputs.command == 'full-process') && inputs.execute == 'true' && '--execute' || '' }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    TRANSFER_TOKEN: ${{ inputs.transfer_token }}

